scst/include/scst.h, scst/src/dev_handlers/scst_vdisk.c
fileio_exec_async() for fileio devices with o_direct flag triggers
the following Linux direct_io datapath:
- fileio_exec_async()      -- ... --> iomap_dio_bio_actor()
- iomap_dio_bio_actor()    -- ... --> bio_iov_iter_get_pages()
- bio_iov_iter_get_pages() -- ... --> iov_iter_get_pages()
- iov_iter_get_pages() returns -EFAULT
iov_iter_get_pages() only handles iovec and bvec iterators.
Its kvec hanlding always return -EFAULT.
We cannot use iovec because calling iov_iter_init() for iovec
from the kernel context initializes iov_iter as ITER_KVEC.
Thus, use bvecs for fileio async direct IO.
Reported-by: Lu Chang
=> vdisk_fileio, async mode: Switch from kvec to bvec

scst/src/scst_lib.c
The ini_unchecked_isa_dma in the scst_alloc_add_tgt_dev() is used
as an uninitialized variable for kernel versions since v5.13.
Fixes: 2a775c42 ("scst: Port to Linux kernel v5.13")
Detected by smatch.
=> scst_lib: Fix use of uninitialized ini_unchecked_isa_dma

scst/src/scst_event.c
scst_event: Fix crash when copying an event from user space
We copy struct scst_event with the payload from user space, but
use event_entry_len as the length of this buffer.
event_entry_len contains the length of struct scst_event_entry and
the payload. struct scst_event is part of struct scst_event_entry
and is therefore shorter in length.
Thus, use the length of struct scst_event + payload when
copying the event from user space.
This patch should fix the following bug:
usercopy: Kernel memory overwrite attempt detected to SLUB object 'kmalloc-512' (offset 232, size 296)!
------------[ cut here ]------------
kernel BUG at mm/usercopy.c:102!
...
RIP: 0010:usercopy_abort+0x74/0x76
Call Trace:
__check_heap_object+0xd3/0x100
__check_object_size+0xff/0x16b …
=> scst_event: Fix crash when copying an event from user space

qla2x00t-32gbit/qla2x00-target/scst_qla2xxx.c
For the old qla2x00 driver, the hw_target attribute allows you to
distinguish hardware and virtual targets.
But for the new qla2x00t-32gbit driver, this attribute turned out
to be broken. Regardless of whether it is a hardware or virtual target,
this attribute is created for that target and always returns 1.
Restore this broken functionality by returning 1 for the hardware target
and 0 otherwise.
=> qla2x00t-32gbit: Restore support for sysfs hw_target attribute

iscsi-scst/doc/manpages/iscsi-scstd.8, iscsi-scst/usr/iscsi_scstd.c, iscsi-scst/usr/iscsid.h
Add the opportunity to globally specify multiple addresses, which
iSCSI/iSER portal will listen on.
There is a way to specify the addresses for a target, on which
portals it will be available, using the allowed_portal parameter.
There is also a way to set this globally via the iscsi-scstd
--address parameter. The problem is that the last option allows
you to specify only one local address. So extend this functionality
to specify more then one address.
Also increase the maximum number of listening addresses to 32.
Signed-off-by: Aleksandr Dyadyushkin <alextalker@ya.ru>
=> iscsi-scstd: Allow to specify multiple addresses the server should listen on

.github/workflows/mail_notification.yml
Google no longer support the use of third-party apps or devices which
ask you to sign in to your Google Account using only your username and
password. This causes problems when using github mail notification action
to send SCST patches. Hence, change the Google mail server to an another one.
=> github: Change mail server for mail notification action

qla2x00t-32gbit/qla2x00-target/qla_tgt.c, qla2x00t-32gbit/qla2x00-target/scst_qla2xxx.c
NPIV port deregistering processing is different from physical port
processing. We use the same handling for both of them, which causes
the crash when it's an NPIV port. Hence separate the common processing
logic depending on the type of port.
Reported-by: Rob Turk <robtu@rtist.nl>
=> qla2x00t-32gbit: Fix crash during deregistering an NPIV port

www/index.html
Replace the broken URL of SCST overview slides with a working URL.
=> www: Update SCST overview slides URL

qla2x00t-32gbit/qla2x00-target/scst_qla2xxx.c
Calling scst_cmd_init_done() with SCST_CONTEXT_DIRECT from
sqa_qla2xxx_handle_cmd() cause a SCST READ commands to stall for
scst_user devices.
The problem is that scst_user devices use udev_cmd_threads for processing
SCST commands, so it's necessary to call the scst_user dev handler
callbacks from the SCST_CONTEXT_THREAD context.
For write commands, this is already done because scst_rx_data() always
processes commands with a THREAD context. But for READ commands, it
depends on passing the preferred context value to scst_cmd_init_done().
So pass the SCST_CONTEXT_THREAD or SCST_CONTEXT_TASKLET to
scst_cmd_init_done(). SCST_CONTEXT_TASKLET would also work, because
the context optimization in scst_init_cmd() will still set SCST_CONTEXT_THREAD
for READ commands.
Reported-by: Eitan Cohen …
=> qla2x00t-32gbit: Change preferred context for scst_cmd_init_done()

qla2x00t-32gbit/qla_target.c
By default the qlini_mode module parameter set initiator mode to 'enabled'.
This forces a SCST user to perform additional steps to activate the target mode.
Therefore, change the default qlini_mode to simplify target mode usage, since
the SCST qla2xxx_scst module is usually only used with it.
=> qla2x00t-32gbit: Change the default qlini_mode to exclusive

scst/README, scst/src/dev_handlers/scst_vdisk.c
The old zero-copy implementation that used zero_copy flag was removed in
commit 19c9aec2 ("vdisk_fileio: Remove the page cache based zero-copy
implementation"). Hence remove this flag since it is no longer used.
=> scst_vdisk: Remove unused zero_copy flag

qla2x00t/qla2x00-target/qla2x00t.c, qla2x00t/qla_os.c
The legacy API wrappers in include/linux/pci-dma-compat.h should go away as
they create unnecessary midlayering for include/linux/dma-mapping.h API.
Instead use dma-mapping.h API directly.
This patch fixes build for linux kernel v5.18.
=> qla2x00t: Remove pci-dma-compat wrapper API

qla2x00t/doc/qla2x00t-howto.html
Qlogic documentation lack of information about initiator and target modes usage.
=> qla2x00t/doc/qla2x00t-howto.html: Add information about initiator and target modes

scst/src/scst_lib.c
This patch fixes the following Coverity complaint:
CID 275306 (#1 of 1): Resource leak (RESOURCE_LEAK)
Variable cwrp going out of scope leaks the storage it points to.
In the scst_cmp_wr_local() function, we don't free 'cwrp' if the next
check after the memory allocation fails. Hence move this check before
allocating memory.
Fixes: 4525b04b2 ("scst: Reject inconsistent COMPARE AND WRITE commands")
=> scst_lib: Fix memory leak reported by Coverity

.mailmap
I have created a new dedicated email address for SCST. So add
information about it.
New email: gleb.chesnokov@scst.dev
=> mailmap: Update Gleb Chesnokov's email address

scst/include/backport.h, scst/src/scst_mem.c
Support for the following mm layer changes in the Linux kernel v6.0:
- e33c267ab70d ("mm: shrinkers: provide shrinkers with names")
=> Port to Linux kernel v6.0

iscsi-scst/resource_agents/SCSTTarget
Extraneous space in "status" breaks resource monitoring:
<action name="status " timeout="10" interval="10" depth="0" />
Fixes: https://github.com/SCST-project/scst/issues/80
=> iscsi-scst: Fix a typo in SCSTTarget RA

scst/include/backport.h, scst/src/scst_mem.c
The register_shrinker() function has begun return non void value since
v3.12 version. So fix the backport of this function for kernel versions
before v3.12.
Fixes: 84bd33f9a18c ("scst_mem: Port to Linux kernel v6.0")
=> scst/include/backport.h: Fix the register_shrinker() backport

scripts/update-version, scst/include/scst_const.h
SCST_VERSION_CODE has not been updated since SCST v3.4 because the update-version script used the wrong file for parsing. Hence fix the update-version script and SCST_VERSION_CODE.
=> scripts/update-version: Update the SCST_VERSION_CODE

scst/include/backport.h
Fixes: https://github.com/SCST-project/scst/issues/77
=> scst/include/backport.h: Fix the build against CentOS 8-stream

scst/include/backport.h, scst/src/scst_lib.c
Sending an INQUIRY with a buffer size 0 to the LUN that does not exist
causes the following kernel panic:
RIP: 0010:sg_init_table+0x1e/0x30
Call Trace:
scst_alloc_sg+0xc3/0x270 [scst]
scst_set_cmd_error+0x8c9/0xa80 [scst]
__scst_init_cmd+0x5c3/0xb80 [scst]
scst_cmd_init_done+0x142/0xae0 [scst]
cmnd_rx_start+0x7f5/0x13d0 [iscsi_scst]
isert_pdu_rx+0x54/0x140 [isert_scst]
isert_recv_completion_handler+0x498/0x580 [isert_scst]
isert_poll_cq+0x396/0x800 [isert_scst]
isert_cq_comp_work_cb+0x4a/0x120 [isert_scst]
process_one_work+0x1d1/0x410 
worker_thread+0x2b/0x3d0
kthread+0x11a/0x130
ret_from_fork+0x1f/0x40
Hence add extra check to avoid the crash.
Reported-by: Lev Vainblat <lev@zadarastorage.com>
=> scst_lib: Handle an INQUIRY with buffer size 0

scst/src/scst_targ.c
1. atomic_inc_return() avoids a race in between atomic_read() & atomic_inc().
2. atomic_inc_return() is a few cycles faster than atomic_inc()/atomic_read() sequence.
=> scst_targ: Use 'atomic_inc_return' to check 'dev->dev_cmd_count'

doc/scst_pg.sgml, scst/include/scst.h, scst/src/scst_main.c
Support for scst_tgt_template detect() method was declared obsolete in 2015. Remove support for scst_tgt_template detect() method.
See also commit 4ac6d7a26d1f ("[PATCH] scst: Drop detect() method").
=> scst: Drop support for detect() method

scst/include/scst.h, scst/src/scst_copy_mgr.c, scst/src/scst_lib.c
Fixes: https://github.com/SCST-project/scst/issues/99
=> scst_copy_mgr: Fix scst_cm_desig_list list corruption

qla2x00t-32gbit/qla_def.h, qla2x00t-32gbit/qla_init.c, qla2x00t-32gbit/qla_inline.h, qla2x00t-32gbit/qla_os.c, qla2x00t-32gbit/qla_target.c
Initialization of vha->unknown_atio_list and vha->unknown_atio_work only
happens for base_vha in qlt_probe_one_stage1(). But there is no
initialization for NPIV hosts that are created in qla24xx_vport_create().
This causes a crash when trying to access these NPIV host fields.
Fix this by adding initialization to qla_vport_create().
Fixes: https://github.com/SCST-project/scst/issues/56
=> qla2x00t-32gbit: Initialize vha->unknown_atio_[list, work] for NPIV hosts

scst/include/backport.h
Unbreak the build for the previous commit against kernel versions before v3.12.
Fixes: ee6312ac5a30 ("scst_vdisk, qla2x00t-32gbit: Use PTR_ERR_OR_ZERO instead of IS_ERR and PTR_ERR")
=> scst: Backport the PTR_ERR_OR_ZERO() function

scst/include/backport.h
Fix a regression introduced during [scst_lib: Port to Linux kernel v5.19](https://github.com/SCST-project/scst/commit/d989aa91f31fa8893b7ee10685f552b3eea8395d) that breaks `dev_disk` operation.
The kernel function `blk_execute_rq_nowait` will set `rq->end_io` to the `done` parameter, so pass in the existing `rq->end_io` rather than NULL to prevent zeroing it.
=> scst/include/backport.h: Do not set rq->end_io to NULL

Makefile, debian/rules, debian/scst.dkms.in
It's quite strange but we can't run `make dpkg` with other debug mode level. Fix that.
=> pass through `DEBUG_MODE_LEVEL` to `dpkg` make target

.github/workflows/ci.yml, .github/workflows/coverity.yml, .github/workflows/mail_notification.yml
This patch should fix the following github warning:
Node.js 12 actions are deprecated. Please update the following
actions to use Node.js 16: actions/checkout@v2
=> github: Update actions/checkout to v3

scst/src/dev_handlers/scst_disk.c, scst/src/scst_local_cmd.c
In certain HA configurations it may be desirable to use `dev_disk` in conjunction with the `cluster_mode` DLM mechanism previously added to `scst_vdisk`.
=> Add cluster_mode support to scst_disk

scst/src/scst_lib.c
In kernel commit [772c8f6f3bbd](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=772c8f6f3bbd) ("Merge tag 'for-4.11/linus-merge-signed' * of git://git.kernel.dk/linux-block") both scsi_init_rq and scsi_init_request (later renamed to scsi_mq_init_request in [e7008ff5c61a](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=e7008ff5c61a)) initialize the scsi_request sense buffer, so we don't need to (nor should) provide our own.
=> scst_lib: Fix sense data regression for pass-through commands.

scst/src/scst_lib.c
In kernel commit [066ff571011d](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=066ff571011d) ("block: turn bio_kmalloc into a simple kmalloc wrapper"), the order of arguments to `bio_kmalloc` changed, as did its "magic autofree semantics".
=> scst_lib: Fix bio_kmalloc usage to match change in Linux kernel v5.19

scst/src/scst_dlm.c, scst/src/scst_priv.h, scst/src/scst_sysfs.c
When `dlm_new_lockspace` is called with a NULL `cluster_name` the kernel will emit an error message "_dlm cluster name '%s' is being used without an application provided cluster name_" on each call.
Therefore, provide a mechanism to set a `cluster_name` and use it when calling `dlm_new_lockspace`.
Since dlm will only have one cluster active on a particular host, make this new scst parameter global.
=> scst_sysfs: Add support for cluster_name

scst/include/backport.h
See also PR https://github.com/SCST-project/scst/pull/132.
=> scst/include/backport.h: Fix the CentOS / RHEL 7.[012345] builds

scst/README, scst/src/dev_handlers/scst_vdisk.c
Add `lb_per_pb_exp` attribute to allow control of whether `READ CAPACITY 16` returns non-zero `LOGICAL BLOCKS PER PHYSICAL BLOCK EXPONENT`.
Certain initiators have difficulty with large physical block sizes.
=> scst_vdisk: Add lb_per_pb_exp attribute

scst/src/dev_handlers/scst_vdisk.c, scstadmin/scstadmin.sysfs/scst-1.0.0/lib/SCST/SCST.pm
Since `cluster_mode` relies upon the `t10_dev_id` to generate a namespace, once `cluster_mode` is set the `t10_dev_id` can no longer be changed.  This reasonable restriction is enforced by `scst_dev_sysfs_pr_file_name_store`.
However, because `cluster_mode` is listed as one of the various _add_dev_params_, this meant that it would be set earlier than `t10_dev_id` when `scstadmin` processes _scst.conf_.  The upshot is that having `cluster_mode 1` in _scst.conf_ means that the `t10_dev_id` is ignored.
Rectify by adding `t10_dev_id` to `fileio_add_dev_params`, etc and modifying the _SCST.pm_ `openDevice `so that `cluster_mode` is set last.
=> scst_vdisk, scstadmin: Allow t10_dev_id to be stored before cluster_mode

scst/include/backport.h
As in #77, SCST fails to install on RHEL 8.8 due to duplicate symbols:
```
[scst-3.7]# make 2release
cd scst && make 2release
make[1]: Entering directory '/root/scst-3.7/scst'
make[1]: Leaving directory '/root/scst-3.7/scst'
[scst-3.7]# make install
if [ install = extraclean ]; then rm -f TAGS tags cscope.out; fi
for d in scst iscsi-scst qla2x00t-32gbit/qla2x00-target srpt        \
scst_local fcst usr scstadmin; do \
make -j$(nproc) -C "$d" install || break;                   \
done
make[1]: Entering directory '/root/scst-3.7/scst'
cd src && make install
make[2]: Entering directory '/root/scst-3.7/scst/src'
make -C certs KDIR=/lib/modules/4.18.0-477.el8.x86_64/build                                     \
make[3]: Entering directory '/root/scst-3.7/scst/src/certs'
openssl req -new -nodes …
```
=> scst/include/backport.h: Fix building on RHEL 8.8

scst/src/scst_lib.c, scst/src/scst_sysfs.c, scst/src/scst_targ.c
We must always protect sess_tgt_dev_list during access and modification.
There are two mechanisms for that:
- tgt_dev_list_mutex for list modifications.
- RCU for read-only list accesses.
Currently, the codebase doesn't consistently apply protection when accessing the list. Fix this by adding RCU protection.
See also commit 3e64094b0c14 ("scst_sysfs: Do not suspend I/O for LUN management").
=> scst: Use RCU read lock when accessing sess_tgt_dev_list

scst/README, scst/include/scst.h, scst/src/scst_lib.c, scst/src/scst_sysfs.c
Add a setting to `scst_tgt` that can prevent `scst_gen_aen_or_ua` from generating an AEN, even if the underlying transport is capable of transmitting them.  It will instead generate a UA.
This could prove useful in different situations, including when the target port is also a _forward_dst_.
(The new _sysfs_ interface was modeled on the code for _forward_dst_.)
=> scst_lib,scst_sysfs: Add aen_disabled setting

scstadmin/scstadmin.spec.in
This patch fixes RPM build errors caused by incorrect file paths:
RPM build errors:
File must begin with "/": %{perl_vendorlib}/SCST
File must begin with "/": %{perl_vendorarch}/auto/SCST_SCST
For some reasons, the perl_vendorlib and perl_vendorarch variables may not be defined by default on newer RHEL systems.
Therefore, assign variables explicitly to avoid these errors.
=> scstadmin.spec: Fix RPM build errors

qla2x00t-32gbit/qla_os.c, qla2x00t/qla_os.c, scst_local/scst_local.c
The previous series of patches introduced the use of a const pointer to scsi_host_template. However, scsi_host_alloc() uses a non-const pointer prior to kernel version 6.4, causing the build to throw the following error:
passing argument 1 of ‘scsi_host_alloc’ discards ‘const’ qualifier
from pointer target type
Hence, cast away the constness to resolve the error.
=> scst: Unbreak the build for kernel versions <= 6.3

iscsi-scst/include/iscsi_scst.h, iscsi-scst/usr/iscsid.c
The iSCSI specification has rules wrt what constitutes a valid initiator name.  Perform some checks and reject LOGINs with an invalid initiator name.
=> scsi-scstd: Check initiator name provided during login

scst/include/scst.h, scst/src/scst_dlm.c, scst/src/scst_dlm.h, scst/src/scst_no_dlm.c, scst/src/scst_pres.c, scst/src/scst_pres.h
Previously, when `scst_pr_send_ua_reg` attempted to deliver a UNIT ATTENTION to a registrant that was on another node in a dlm-based HA cluster, the unit attention was dropped.
This breaks, for example, _SPC-5 5.14.12.2.2 Releasing_ 
> if the NUAR bit (see 7.5.11) is set to zero and the released persistent reservation is either a registrants 
> only type or an all registrants type persistent reservation, then the device server shall establish a unit 
> attention condition for the SCSI initiator port associated with every registered I_T nexus other than I_T 
> nexus on which the PERSISTENT RESERVE OUT command with RELEASE service action was 
> received, with the additional sense code set to RESERVATIONS RELEASED
Rectify by adding a `pr_reg_queue_rem_ua` function to `struct scst_cl_ops` and …
=> scst_pres,scst_dlm: Fix broken UNIT ATTENTION for remote PR registrants

iscsi-scst/kernel/isert-scst/iser.h, scst/src/scst_lib.c, scst/src/scst_targ.c, srpt/src/ib_srpt.h
The SCST has dropped support for RHEL5/6 since v3.6.
=> scst: Remove support for RHEL5/6

scst/include/backport.h
Fixes: https://github.com/SCST-project/scst/issues/167
=> scst/include/backport.h: Unbreak the RHEL 9.3 build

scst/src/scst_dlm.c, scst/src/scst_main.c, scst/src/scst_priv.h, scst/src/scst_sysfs.c
Fix the following compiler error:
ERROR: modpost: "scst_dlm_cluster_name" [...] undefined!
The error occurs because the declaration of scst_dlm_cluster_name is located in the scst_dlm.c file, but it's used in the scst_sysfs.c file. As a result, when building without DLM, this variable lacks a declaration.
To resolve this, the declaration is moved to the scst_main.c file, and the variable scst_dlm_cluster_name is renamed to scst_cluster_name.
Fixes: 00f31004ab2b ("scst_sysfs: Add support for cluster_name")
=> scst: Unbreak the non-DLM build

.github/workflows/checkpatch_pull.yml, .github/workflows/checkpatch_push.yml, scst/include/backport.h, scst/src/scst_main.c, scst/src/scst_priv.h
This patch replaces percpu_ref_kill() with percpu_ref_kill_and_confirm() to guarantee safe usage of references in atomic mode immediately afterwards.
This change ensures accurate checking of active commands following the initial reference killing.
Reported-by: Lev Vainblat <lev@zadarastorage.com>
=> scst: Confirm percpu refs has scheduled and switched to atomic

iscsi-scst/kernel/target.c, qla2x00t-32gbit/qla_init.c, qla2x00t-32gbit/qla_mr.c, qla2x00t/qla_gs.c, qla2x00t/qla_init.c, qla2x00t/qla_nx.c, qla2x00t/qla_os.c, scst/include/backport.h, scst/src/dev_handlers/scst_user.c, scst/src/dev_handlers/scst_vdisk.c, scst/src/scst_debug.c, scst/src/scst_event.c, scst/src/scst_main.c, scst/src/scst_mem.c, scst/src/scst_tg.c, srpt/src/ib_srpt.c
strlcpy() reads the entire source buffer first. This read may exceed the destination size limit. This is both inefficient and can lead to linear read overflows if a source string is not NULL-terminated [1].
[1] https://www.kernel.org/doc/html/latest/process/deprecated.html#strlcpy
=> scst: Replace all strlcpy() with strscpy()

iscsi-scst/README, iscsi-scst/usr/config.c, iscsi-scst/usr/ctldev.c, iscsi-scst/usr/event.c, iscsi-scst/usr/iscsid.c, iscsi-scst/usr/iscsid.h, iscsi-scst/usr/isns.c, iscsi-scst/usr/param.h
This includes both support during iSCSI LOGIN and iSNS.
----
A couple of caveats...
BTW, my local run of _checkpatch.pl_ was giving a warning:
```
WARNING:STRLCPY: Prefer strscpy over strlcpy - see: https://github.com/KSPP/linux/issues/89
#84: FILE: iscsi-scst/usr/ctldev.c:126:
+       strlcpy(kern_attrs[i].name, ISCSI_TARGET_ALIAS_ATTR_NAME,
```
However, since this is in **user-space** code rather than kernel, **strscpy** is not available!  I know we could have _checkpatch.pl_ always ignore `STRLCPY`, but I was wary about doing that as it'd do away with the check for kernel code too.
As documented [here](https://github.com/open-iscsi/target-isns/blob/master/documentation/iSNS-servers.md), the Windows iSNS server doesn't handle updates very well - now including alias updates.  OTOH, from …
=> Add support for iSCSI TargetAlias

scst/src/scst_mem.c, scst/src/scst_mem.h
Support for the following mm layer changes in the Linux kernel v6.7:
- c42d50aefd17 ("mm: shrinker: add infrastructure for dynamically allocating shrinker")
=> scst_mem: Port to Linux kernel v6.7

scst/src/scst_targ.c
This patch should fix the following UBSAN warning:
UBSAN: shift-out-of-bounds in scst/src/scst_targ.c:3912:6 shift exponent -1 is negative
Call Trace:
<TASK>
show_stack+0x52/0x5c
dump_stack_lvl+0x4a/0x63
dump_stack+0x10/0x16
ubsan_epilogue+0x9/0x36
__ubsan_handle_shift_out_of_bounds.cold+0x61/0xef
scst_process_active_cmd.cold+0xf/0x2d [scst]
scst_process_redirect_cmd+0xd4/0x2e0 [scst]
scst_tgt_cmd_done+0x48/0x70 [scst]
scst_local_targ_xmit_response+0x64/0x220 [scst_local]
scst_process_active_cmd+0x891/0x2140 [scst]
scst_process_redirect_cmd+0xd4/0x2e0 [scst]
scst_cmd_done_local+0x80/0x110 [scst]
dev_user_process_reply+0x597/0x1160 [scst_user]
dev_user_ioctl+0x145/0xb23 [scst_user]
__x64_sys_ioctl+0x95/0xd0
do_syscall_64+0x5c/0xc0
entry_SYSCALL_64_after_hwframe+0x62/0xcc
Reported-by: Rob …
=> scst_targ: Fix shift out of bounds

scst/include/scst.h, scst/src/dev_handlers/scst_disk.c, scst/src/scst_targ.c
`scst_pass_through_cmd_done` can run in interrupt context, and call `scst_replace_port_info`, which in turn was calling `scst_lookup_tg_id`. Since `scst_lookup_tg_id `does a `mutex_lock`, we should **not** call it from interrupt context.
The call path was added in https://github.com/SCST-project/scst/commit/e72eae316aeef2743cad70ed955e5b7f4ddca249 and could lead to:
```
BUG: scheduling while atomic: swapper/14/0/0x00000102
Preemption disabled at:
Call Trace:
[<ffffffffa1d1b146>] ___slab_alloc.constprop.0+0x4d6/0x750
<IRQ>
dump_stack_lvl+0x44/0x5c
__schedule_bug.cold+0x80/0x8d
__schedule+0x76c/0x860
schedule+0x5a/0xb0
schedule_preempt_disabled+0x14/0x30
__mutex_lock.constprop.0+0x6ce/0x700
scst_lookup_tg_id+0x19/0xa0 [scst]
scst_pass_through_cmd_done+0x14f/0x2e0 [scst] …
```
=> scst.h, scst, device handlers: Fix scst_replace_port_info

qla2x00t-32gbit/qla_os.c, scst/include/backport.h, scst/src/dev_handlers/scst_vdisk.c, scst/src/scst_lib.c
Support for the following block layer changes in the Linux kernel v6.8:
- e719b4d15674 ("block: Provide bdev_open_* functions")
- cd34758c5238 ("block: Remove blkdev_get_by_*() functions")
=> Port to Linux kernel v6.8

.gitignore, scst/src/dev_handlers/scst_vdisk.c
Suppress the following (false positive) Coverity complaint:
CID 347415: (#1 of 1): Dereference after null check (FORWARD_NULL)
var_deref_model: Passing null pointer virt_dev->bdev_handle to
bdev_release_backport, which dereferences it
=> scst_vdisk: Fix check for blockio device

scst/src/dev_handlers/scst_vdisk.c
A recent commit (974001f66) added backport support for `bdev_open_by_path`. This entailed adding a `struct bdev_handle`, but in `vdisk_exec_read_capacity16` the code attempts to lookup `virt_dev->bdev_handle->bdev` without regard for the fact that if we are not using blockio then `bdev_handle` will be null.  Rectify by making the lookup more robust.
=> scst_vdisk: Fix recent breakage in vdisk_exec_read_capacity16

scst/src/dev_handlers/scst_vdisk.c
This patch simplifies the retrieval of the request_queue within the vdisk_exec_read_capacity16 function.
=> scst_vdisk: Simplify request_queue retrieval in vdisk_exec_read_capacity16

iscsi-scst/README, iscsi-scst/usr/event.c, iscsi-scst/usr/iscsi_scstd.c, iscsi-scst/usr/iscsid.h, iscsi-scst/usr/param.h, iscsi-scst/usr/target.c
Add a `link_local` parameter to control whether an IPv6 `SendTargets` response includes link local addresses.  The default is to preserve the existing behavior and include them.
----
There could be several reasons why including link local addresses might **not** be desirable, incl:
- They are not routable
- Currently _open-iscsi_ has a bug whereby a link-local addresses included in SendTargets response may break the handling on the client, preventing discovery from working even if global IPv6 addresses are also available.  This will manifest if the response includes a zone-index naming an interface that is not available on the client.
Wrt the latter: over the years there have been various attempts to have this addressed from various directions  (e.g. in Ubuntu …
=> iscsi-scst: Add link_local parameter

.gitignore, scst/include/scst.h, scst/src/dev_handlers/scst_vdisk.c, scst/src/scst_lib.c
Support for the following block layer changes in the Linux kernel v6.9:
- f3a608827d1f ("bdev: open block device as files")
- b1211a25c4fe ("bdev: make bdev_{release, open_by_dev}() private to block layer")
=> scst_lib, scst_vdisk: Port to Linux kernel v6.9

iscsi-scst/usr/param.c
Writing the string `:default:` to the _/sys_ entry will restore `local_def`
```
root@cluster1:~# cat /sys/kernel/scst_tgt/targets/iscsi/iqn.2005-10.org.freenas.ctl:test1/DataDigest
None
root@cluster1:~# echo CRC32C > /sys/kernel/scst_tgt/targets/iscsi/iqn.2005-10.org.freenas.ctl:test1/DataDigest
root@cluster1:~# cat /sys/kernel/scst_tgt/targets/iscsi/iqn.2005-10.org.freenas.ctl:test1/DataDigest
CRC32C
[key]
root@cluster1:~# echo ':default:' > /sys/kernel/scst_tgt/targets/iscsi/iqn.2005-10.org.freenas.ctl:test1/DataDigest
root@cluster1:~# cat /sys/kernel/scst_tgt/targets/iscsi/iqn.2005-10.org.freenas.ctl:test1/DataDigest
None
root@cluster1:~#
root@cluster1:~# cat /sys/kernel/scst_tgt/targets/iscsi/iqn.2005-10.org.freenas.ctl:test1/MaxRecvDataSegmentLength
1048576
root@cluster1:~# echo 8192 …
```
=> iscsi-scst: Add mechanism to restore target parameter to default

scst/src/scst_lib.c
Initiators will attempt to send LUN 0 INQUIRY and REPORT LUNS commands when connecting to a target.  If a SCST target is configured with LUNs e.g. 100, 101 (i.e. no LUN 0) then disks would **NOT** surface when `iscsiadm` is used to login on Linux.  This PR is to modify SCST behavior to rectify this.
- Add `scst_set_lun_not_supported_report_luns` to handle the case when REPORT LUNs is sent to an unsupported LUN.
- Also, in `scst_set_lun_not_supported_inquiry` report a valid vendor identification string to promote better initiator behavior.
Tested with SCST running on:
- Linux 6.1.20
- Linux 6.6.16
Tested with clients:
- Linux kernel 6.6.16 / iscsiadm version 2.1.8
- Linux kernel 5.10.191 / iscsiadm version 2.1.3
- Windows 11
----
https://github.com/open-iscsi/open-iscsi/issues/175 is not …
=> scst_lib: Allow REPORT LUNS to operate on an unsupported LUN

scst/src/scst_lib.c
When SCST receives an INQUIRY request for an incorrect LUN, it calls scst_set_lun_not_supported_inquiry(), which returns an inquiry buffer with a peripheral qualifier of 011b and a peripheral device type of 1Fh. However, for a VPD inquiry, it is unable to populate the remaining fields. According to SPC-6, if the device server cannot return the requested data, it should terminate with CHECK CONDITION.
Reported-by: Lev Vainblat <lev@zadarastorage.com>
=> scst_lib: Fix VPD inquiry handling on incorrect LUNs

iscsi-scst/README, iscsi-scst/usr/event.c, iscsi-scst/usr/iscsi_scstd.c, iscsi-scst/usr/iscsid.c, iscsi-scst/usr/iscsid.h, iscsi-scst/usr/param.h
Add an `internal_portal` parameter to allow specified portals to bypass CHAP controls for both discovery and target login.  If not populated, then the current behavior will be preserved.
This is particularly useful for "internal" targets used as part of ALUA configuration (only presented on an internal, private portal).  It is envisaged that typical use would only be for those ALUA internal targets, and that `internal_portal` would only be set **once** (most likely to a single IP address, the private portal IP).  The main issue being addressed/avoided is that discovery auth is currently _global_.
=> iscsi-scst: Add internal_portal parameter

scst/include/backport.h, scst/src/dev_handlers/scst_tape.c, scst/src/scst_lib.c
Res on RHEL 9.5
There were 3 files that needed additional/updated conditional build checks for RHEL 9.5. 
These places already had some conditional checks, but more were needed since some of the upstream kernel changes have been pulled into the 5.14.0 kernel that RHEL 9.5 is using.
Files changed:
scst/include/backport.h +285
scst/src/scst_lib.c +6088 and +6116
scst/src/dev_handlers/scst_tape.c +178
See the below compiler output before and after the fixes (intermediate failures are shown as I fixed them one by one):
```
[scst-3.9.0]# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.5 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.5"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.5 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon" …
```
=> backport.h, scst_tape.c, scst_lib.c: Fix build failures on RHEL9.5

scst/src/scst_lib.c, scst/src/scst_priv.h
This patch refactors the code by accumulating the target devices into a temporary list and moving the synchronize_rcu() call outside of the loops. By doing so, we reduce the number of synchronize_rcu() calls to one, improving the efficiency of the cleanup process.
Fixes: https://github.com/SCST-project/scst/issues/229
=> scst_lib: Move synchronize_rcu() calls out of loops to reduce overhead

scstadmin/scstadmin.sysfs/scstadmin
In out of "scstadmin -list_sessions" cmd occurs error "Use of uninitialized value in numeric lt (<) at /usr/local/sbin/scstadmin line 3679"
=> FIX scstadmin -list_sessions error msg in out cmd

scstadmin/scstadmin.sysfs/scstadmin
In out of "scstadmin -list_sessions" cmd occurs error "Use of uninitialized value in numeric lt (<) at
/usr/local/sbin/scstadmin line 3679".
=> scstadmin: Fix scstadmin -list_sessions error msg in out cmd

iscsi-scst/kernel/conn.c
This will make it possible to distinguish `iSCSI-TCP` connections from `iSER` connections.
(It is possible that the _same_ interface/IP could be used for either.)
=> iscsi-scst: Add transport name to sys entry for connection

iscsi-scst/usr/Makefile, iscsi-scst/usr/af_alg.c, iscsi-scst/usr/af_alg.h, iscsi-scst/usr/chap.c
At the moment SCST contains support for 2 CHAP algorithms: MD5 and SHA1.  Linux LIO and open-iscsi both include these, as well as SHA256 and SHA3-256 (since 2019).
This PR adds SHA256 and SHA3-256 support to CHAP.  Since in SCST CHAP negotiation is performed by the userspace `iscsi-scstd` daemon, the PR uses the kernel userspace `AL_ALG` API to access the additional hash functions.
If configured for CHAP, on iSCSI login the client will present an ordered list of desired algorithms.  During this negotiation, if the client requests SHA256 or SHA3-256 we verify that the kernel supports the algorithm before agreeing to use it.
----
Did some testing using `open-iscsi` with target settings modified from the default, e.g.
```
node.session.auth.chap_algs = SHA256
node.session.auth.username = …
```
=> iscsi-scst: Add SHA256 and SHA3-256 support to CHAP

iscsi-scst/Makefile, iscsi-scst/usr/iscsid.h, scst-dkms.spec.in, scst.spec.in, scst/include/backport.h, scst/src/scst_lib.c, scstadmin/scstadmin.spec.in, scstadmin/scstadmin.sysfs/Makefile
GCC 15 (C23) now reserves bool/true/false, so the local typedef in iscsid.d breaks the build:
error: cannot use keyword 'false' as enumeration constant
error: expected ';', identifier or '(' before 'bool'
Include <stdbool.h> and drop the typedef.
=> iscsi-scstd: Fix redefinition of bool when building with GCC 15

Makefile
Sync the `help` target with the actual Makefile rules:
- Include missing targets (tags, cov-build, docs, scstadm, scstadm-rpm)
- Reorder and align target groups
- Update `.PHONY` list
=> Makefile: Actualise help target

iscsi-scst/usr/iscsi_scstd.c, scstadmin/init.d/scst
When attempting to manage iscsi-scstd using a systemd service file, systemd warns:
PIDFile= references a path below legacy directory /var/run/, [...]
Change the pidfile path to be under /run instead.
/run has been in use as a replacement for /var/run for many years now (the original Debian proposal is from 2011). Most distributions symlink /var/run to /run, which means that this change should not have any adverse side effects for the vast majority of users.
=> iscsi-scst: use /run instead of /var/run
